package hr.kitiva.beauty.nail;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.InputStream;
import java.math.BigDecimal;
import java.util.List;

/**
 * Vertical slice — the hand-scoped HR nail pilot catalog.
 *
 * <p><strong>Why this is separate from the furniture {@code products} table.</strong> The pilot exists to
 * prove the product experience, not to exercise the import pipeline. Routing 26 rows through
 * {@code ProductImportService} would mean giving every nail polish a {@code roomTags} and {@code styleTags}
 * value (both NOT NULL, and both required by {@code canEnterPlanner}) purely to satisfy a furniture-shaped
 * schema. That is schema theatre. Wiring the pilot into the shared table and its validation is real work
 * and is deliberately deferred until the experience is proven worth building.</p>
 *
 * <p><strong>Provenance.</strong> Generated by {@code scripts/build-nail-pilot-catalog.mjs} from Golden Rose
 * HR's public Shopify {@code /products.json} — a published JSON endpoint, not a page scraped past a block.
 * Names, prices, shades, stock, URLs and images are as the retailer publishes them. They are machine-captured
 * and <em>not</em> hand-checked, which is why every row carries {@code dataQuality: "pilot-unreviewed"}.</p>
 */
@Component
public class NailPilotCatalog {

    private static final Logger log = LoggerFactory.getLogger(NailPilotCatalog.class);
    static final String RESOURCE = "/catalog/nail-pilot-hr.json";

    private final Pilot pilot;

    public NailPilotCatalog() {
        this(RESOURCE);
    }

    NailPilotCatalog(String resource) {
        Pilot loaded = null;
        try (InputStream in = NailPilotCatalog.class.getResourceAsStream(resource)) {
            if (in != null) loaded = new ObjectMapper().readValue(in, Pilot.class);
        } catch (Exception ex) {
            log.warn("Nail pilot catalog could not be loaded from {}: {}", resource, ex.getMessage());
        }
        this.pilot = loaded;
        log.info("Nail pilot catalog: {} product(s)", products().size());
    }

    public List<PilotProduct> products() {
        return pilot == null ? List.of() : pilot.products();
    }

    /**
     * Rows that may actually be offered for a slot: in stock AND consumer-eligible. Out-of-stock and
     * professional-only rows stay in the catalog on purpose, so the assembler has to reject them rather
     * than be handed a pre-filtered world.
     */
    public List<PilotProduct> availableForSlot(String slot) {
        return products().stream()
                .filter(p -> p.kitSlot().equalsIgnoreCase(slot))
                .filter(PilotProduct::inStock)
                .filter(PilotProduct::consumerSafe)
                .toList();
    }

    /** As {@link #availableForSlot} but restricted to one nail system ("both" rows always qualify). */
    public List<PilotProduct> availableForSlot(String slot, String system) {
        return availableForSlot(slot).stream()
                .filter(p -> system == null || system.isBlank()
                        || system.equalsIgnoreCase(p.nailSystem()) || "both".equalsIgnoreCase(p.nailSystem()))
                .toList();
    }

    public List<PilotProduct> forSlot(String slot) {
        return products().stream().filter(p -> p.kitSlot().equalsIgnoreCase(slot)).toList();
    }

    /** Distinct retailers in the pilot, for provenance copy. */
    public List<String> retailers() {
        return products().stream().map(PilotProduct::retailer).filter(java.util.Objects::nonNull).distinct().toList();
    }

    public boolean isLoaded() {
        return pilot != null && !products().isEmpty();
    }

    public String capturedAt() {
        return pilot == null ? "" : pilot.capturedAt();
    }

    public String retailer() {
        return String.join(" + ", retailers());
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record Pilot(String capturedAt, String market, String currency, List<String> systems,
                 List<Source> sources, List<PilotProduct> products) {
        Pilot {
            products = products == null ? List.of() : List.copyOf(products);
            sources = sources == null ? List.of() : List.copyOf(sources);
            systems = systems == null ? List.of() : List.copyOf(systems);
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record Source(String retailer, String endpoint, String platform, String method,
                         String verificationMethod, String status, String lastVerifiedAt, String note) { }

    /** The sources this catalog was built from, with the reachability recorded by the capture run. */
    public List<Source> sources() {
        return pilot == null ? List.of() : pilot.sources();
    }

    /**
     * One pilot row.
     *
     * @param shadeColorKnown whether the retailer names this shade's colour. Measured false for every shade
     *                        in this pilot — Golden Rose numbers them ("Keratin 42") and publishes only a
     *                        swatch image. So a colour request can be answered with a CANDIDATE plus the
     *                        swatch, never with a claim that it matches.
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record PilotProduct(
            String externalId,
            String name,
            String brand,
            String shadeName,
            String shadeCode,
            String retailer,
            String retailerUrl,
            BigDecimal price,
            String previousPrice,
            boolean inStock,
            /** False when the retailer publishes no stock field at all - dm.hr does not. */
            Boolean stockKnown,
            String productUrl,
            String imageUrl,
            String swatchImageUrl,
            String gtin,
            String nailSystem,
            String applicationRole,
            String kitSlot,
            String colorFamily,
            Boolean shadeColorKnown,
            Boolean professionalOnly,
            Boolean consumerEligible,
            /** Published tip count / size range for a press-on set. Null when the retailer does not say. */
            String sizeInfo,
            /**
             * The retailer's own published application instructions, verbatim. Null when the retailer
             * publishes none — which is itself evidence, and is treated as "not proven" rather than
             * "probably fine". {@link NailCapabilityEvidence} reads this to decide whether a brush-on
             * product can claim a cat-eye: that effect is made by dragging a MAGNET through the wet
             * coat, so a polish that never mentions a magnet cannot produce it however it is marketed.
             */
            String applicationEvidence,
            String hemaStatus,
            String tpoStatus,
            Boolean inciPublished,
            String verifiedAt,
            /**
             * How this row was verified: {@code automatic} (machine-read from the retailer's published
             * feed) or {@code manual} (a human opened the page and checked it). Every row in the pilot is
             * automatic, which is the same admission {@code dataQuality: "pilot-unreviewed"} makes.
             */
            String verificationMethod,
            /**
             * The instant this row was last actually READ from its source, as an ISO-8601 instant. A run
             * that could not reach the source does not update it — carrying today's date on a row nobody
             * could check would be the one lie that makes every other field untrustworthy.
             */
            String lastVerifiedAt,
            /** {@code reachable} | {@code temporarily-blocked} | {@code unavailable}, as of the last run. */
            String sourceStatus,
            String dataQuality
    ) {
        public PilotProduct {
            kitSlot = kitSlot == null ? "" : kitSlot.trim().toLowerCase();
            nailSystem = nailSystem == null ? "" : nailSystem.trim().toLowerCase();
            price = price == null ? BigDecimal.ZERO : price;
        }

        /** True when the retailer publishes no stock field, so the UI must tell the user to check. */
        public boolean stockUnverified() {
            return !Boolean.TRUE.equals(stockKnown);
        }

        /** True when this product may enter a consumer kit at all. Fails closed on a missing flag. */
        public boolean consumerSafe() {
            return Boolean.TRUE.equals(consumerEligible) && !Boolean.TRUE.equals(professionalOnly);
        }

        /** Price in integer cents — the unit every total in the beauty engine uses. */
        public int priceCents() {
            return price.multiply(BigDecimal.valueOf(100)).setScale(0, java.math.RoundingMode.HALF_UP).intValue();
        }

        /** A shade whose colour the retailer does not name, so it can only ever be offered as a candidate. */
        public boolean shadeNeedsSwatchCheck() {
            return "color".equals(kitSlot) && !Boolean.TRUE.equals(shadeColorKnown);
        }

        public String displayName() {
            return shadeName == null || shadeName.isBlank() ? name : name + " — " + shadeName;
        }
    }
}
